### ISSUE TITLE
bug: Google OAuth Sign in

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/auth-sveltekit#13]
- [ ] Affter signing up via Google OAuth, You will be redirected to /login. 
- [ ] When attempting to login using GoogleOAuth, it returns an error saying the route `/oauth/google/verify` does not exist
- [ ] Sign In with Google button continues to show loading spinner indefinitely

![image](https://github.com/daedalus-developers/auth-sveltekit/assets/128191960/bc4d44b4-e0bc-4f4b-b3a6-76992cfef6ce)
```ts
app.k1w7G7yF.js:7 Error: Not found: /oauth/google/verify
    at z (entry.DQbvnU7h.js:1:18406)
    at it (entry.DQbvnU7h.js:1:10701)
    at tn (entry.DQbvnU7h.js:1:21194)
    at Array.<anonymous> (oauth-form.DyBtCUSN.js:1:3353)
    at HTMLButtonElement.l (oauth-form.DyBtCUSN.js:1:2073)
    at scheduler.DSoK1I7s.js:1:8410
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.ce (scheduler.DSoK1I7s.js:1:8397)
    at HTMLButtonElement.u (button.CPUUyFYU.js:1:5765)
    at scheduler.DSoK1I7s.js:1:8410
    
```

![image](https://github.com/daedalus-developers/auth-sveltekit/assets/128191960/d37bb939-814d-48c3-bf8a-fb59b84368c9)

**Comment by directormac** [comment]
closed by #12 , although unrelated to that pr.
